from __future__ import annotations

MAGIC = b"\xAA\x55"
FRAME_HEADER_SIZE = 6
CRC_SIZE = 2
FRAME_OVERHEAD = FRAME_HEADER_SIZE + CRC_SIZE
MAX_PAYLOAD_LENGTH = 512

DEFAULT_ACK_TIMEOUT_MS = 100
DEFAULT_MAX_RETRIES = 3
DEFAULT_STATE_HZ = 10

MOVE_SCALE = 100
ANGLE_SCALE = 100

