name: robot_app
description: Sample Flutter app for Robot OS Lite.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_sdk:
    path: ../../mobile_sdk
  hand_gesture_sdk:
    path: hand_gesture_sdk
  voice_control_sdk:
    path: voice_control_sdk
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
